// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "27c3c719-2175-487a-9846-1db896a635d1";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onBEDROOMChange();
void onHALLChange();
void onKITCHENChange();
void onWASHROOMChange();

CloudSwitch bEDROOM;
CloudSwitch hALL;
CloudSwitch kITCHEN;
CloudSwitch wASHROOM;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(bEDROOM, READWRITE, ON_CHANGE, onBEDROOMChange);
  ArduinoCloud.addProperty(hALL, READWRITE, ON_CHANGE, onHALLChange);
  ArduinoCloud.addProperty(kITCHEN, READWRITE, ON_CHANGE, onKITCHENChange);
  ArduinoCloud.addProperty(wASHROOM, READWRITE, ON_CHANGE, onWASHROOMChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
